input-ipc-server = /tmp/mpvsocket

save-position-on-quit=yes

cache=yes
cache-dir=/home/unknown/.cache/mpv/
cache-on-disk=yes
demuxer-max-bytes=512M

[1080p]
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
