#!/bin/sh

swaybg --image "wallpaper.jpg" &
dunst &
wlsunset -l "51.2" -L "6.78" &
wlr-randr --output "XV-5" --pos "1337,0" --output "HDMI-A-1" --pos "0,0" & 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
swayidle -w \
    timeout 300 '$HOME/Scripts/toggle-monitors.sh' \
    timeout 900 'swaylock -f' \
    resume '$HOME/Scripts/toggle-monitors.sh'
