#! /bin/sh

setxkbmap br &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -b &
/usr/bin/dunst &
sh /home/unknown/.config/polybar/launch.sh &
sh /home/unknown/Documents/tflo.sh &
redshift-gtk &
nitrogen --restore &
(ps x | grep bspswallow | grep -v grep) || $HOME/.config/bspwm/scripts/bspswallow &
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 0 

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating
#bspc rule -a feh state=floating
bspc rule -a xdman-Main state=floating
bspc rule -a galculator state=floating
